import 'package:flutter/material.dart';

const MANAGED_PRODUCTS_ADDEDIT_ICO_SAVE_APPBAR = Icon(Icons.save);

const MANAGED_PRODUCTS_ADDEDIT_TITLEPAGE_ADD = "Add Product";
const MANAGED_PRODUCTS_ADDEDIT_TITLEPAGE_EDIT = "Edit Product";

const MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE = "Title";
const MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE = "Price";
const MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT = "Description";
const MANAGED_PRODUCTS_ADDEDIT_IMAGE_TITLE = "Image";
const MANAGED_PRODUCTS_ADDEDIT_FIELD_IMAGE_URL = "Image URL";
