
import '../../../pages_texts_icons/cart.dart';

const CART_TIT_APPBAR = CART_TITLE_APPBAR;
const CART_LBL_CARD = CART_LABEL_CARD;
const CART_LBL_ORDER = CART_LABEL_ORDER;

const CART_ICO_CLEARALL = CART_ICON_CLEAR_ALL;
const CART_ICO_CLEARALL_TOLTIP = CART_ICON_TOOLTIP_CLEAR_ALL;

const CART_ICO_DESMISS = CART_ICON_DESMISSING;
const CART_LBL_CONFIRM_DESMISS = CART_LABEL_DESMISSING_CONFIRMATION;
const CART_MSG_CONFIRM_DESMISS = CART_MESSAGE_DESMISSING_CONFIRMATION;
