name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:

  sdk: '>=2.12.0 <3.0.0'


dependencies:
  mockito: 5.0.12
  flutter:
    sdk: flutter
  intl: 0.17.0
  wc_form_validators: 1.0.0
  string_validator: 0.3.0
  shared_preferences: 2.0.6
  get: 4.1.4
  http: ^0.13.4
  shadow: 1.0.0
  faker: 2.0.0
  currency_textfield: 2.0.0
  json_annotation: 4.0.1
  network_image_mock: ^2.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  effective_dart: 1.3.2
  build_runner: 2.0.6
  json_serializable: 4.1.3

flutter:
  uses-material-design: true

