# DART COMMANDS:
# - dart pub cache clean
# - flutter pub remove package_name
# - flutter clean
name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:

  sdk: '>=2.12.0 <3.0.0'


dependencies:
  mockito: 5.0.16
  flutter:
    sdk: flutter
  intl: 0.17.0
  wc_form_validators: 1.0.0
  string_validator: 0.3.0
  get: ^4.6.1
  get_storage: ^2.0.3
  http: 0.13.4
  shadow: 1.0.0
  faker: 2.0.0
  currency_textfield: 2.0.0
  json_annotation: ^4.5.0
  network_image_mock: 2.0.1
  flutter_staggered_animations: 1.0.0
  animations: 2.0.2
  photo_view: ^0.13.0
  add_to_cart_animation: ^1.0.1
  expandable: ^5.0.1
  google_fonts: ^2.1.1
  path_provider: ^2.0.8
  flutter_platform_widgets: ^1.20.0
  flutter_barcode_scanner: ^2.0.0
  flutter_beep: ^1.0.0
  flutter_mobx: ^2.0.5
  geolocator: ^8.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  effective_dart: 1.3.2
  flutter_lints: ^1.0.4
  mobx_codegen: 2.0.6
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/apple.png
    - assets/images/circular_placeholder.gif

  fonts:
    - family: barcode
      fonts:
        - asset: assets/fonts/barcode_scan.ttf