name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flushbar: 1.10.4
  intl: 0.16.1
  wc_form_validators: 0.1.1
  string_validator: 0.1.4
  shared_preferences: 0.5.7+3
  get: 3.3.0
  dio: 3.0.9
  lombok: ^0.0.5
  http: ^0.012.0+2
  shadow: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: 1.2.3
  build_runner: 1.7.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
