name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:
<<<<<<< Updated upstream
  sdk: '>=2.10.0 <3.0.0'
=======
  sdk: ">=0.9.2 <3.0.0"
>>>>>>> Stashed changes

dependencies:
  mockito:
  flutter:
    sdk: flutter
  flushbar: 1.10.4
  intl: 0.16.1
  wc_form_validators: 0.1.1
  string_validator: 0.1.4
  shared_preferences: 0.5.7+3
  get: 3.22.2
  http: ^0.12.2
  shadow: ^0.1.5
  faker: ^1.3.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  effective_dart: 1.2.3
  image_test_utils: ^1.0.0

flutter:
  uses-material-design: true