name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:

  sdk: '>=2.10.0 <3.0.0'


dependencies:
  mockito:
  flutter:
    sdk: flutter
  flushbar: 1.10.4
  intl: 0.16.1
  wc_form_validators: 0.1.1
  string_validator: 0.1.4
  shared_preferences: 0.5.7+3
  get: 3.22.2
  http: ^0.13.3
  shadow: ^0.1.5
  faker: ^1.3.0
  json_annotation: ^4.0.1


dev_dependencies:
  integration_test: ^1.0.2+3
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
  image_test_utils: ^1.0.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true