name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  mockito:
  flutter:
    sdk: flutter
  flushbar: 1.10.4
  intl: 0.16.1
  wc_form_validators: 0.1.1
  string_validator: 0.1.4
  shared_preferences: 0.5.7+3
  get: 3.3.0
  http: ^0.012.0+2
  shadow: ^0.1.5
  faker: ^1.2.1

dev_dependencies:
  effective_dart: 1.2.3
  build_runner: 1.7.2
  flutter_driver:
    sdk: flutter
  test:

flutter:
  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
