name: shopingapp
description: A new Flutter project.

version: 1.0.0+1

environment:

  sdk: '>=2.12.0 <3.0.0'


dependencies:
  mockito: 5.0.16
  flutter:
    sdk: flutter
  intl: 0.17.0
  wc_form_validators: 1.0.0
  string_validator: 0.3.0
  shared_preferences: 2.0.8
  get: 4.3.8
  http: 0.13.4
  shadow: 1.0.0
  faker: 2.0.0
  currency_textfield: 2.0.0
  json_annotation: 4.3.0
  network_image_mock: 2.0.1
  flutter_staggered_animations: 1.0.0
  animations: 2.0.2
  photo_view: ^0.13.0
  add_to_cart_animation: ^0.0.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  effective_dart: 1.3.2
  build_runner: 2.1.5
  json_serializable: 6.0.1

flutter:
  uses-material-design: true

  assets:
    - apple.png