import 'package:flutter/material.dart';

const MANAGED_PRODUCTS_APPBAR_ADDBUTTON_KEY =
    'managed_products_addedit_appbar_add_button';
const K_MP_ADD_BTN = MANAGED_PRODUCTS_APPBAR_ADDBUTTON_KEY;

const MANAGED_PRODUCTS_DELETEITEM_BUTTON_KEY = 'man_prods_delitem_button_key';
const K_MP_DEL_BTN = MANAGED_PRODUCTS_DELETEITEM_BUTTON_KEY;

const MANAGED_PRODUCTS_UPDATEITEM_BUTTON_KEY = 'man_prods_update_button_key';
const K_MP_UPD_BTN = MANAGED_PRODUCTS_UPDATEITEM_BUTTON_KEY;

const MANAGED_PRODUCT_ITEM_KEY = 'managed_product_item_key';
const K_MP_ITEM_KEY= MANAGED_PRODUCT_ITEM_KEY;

//MANAGED-PRODUCTS-ADD-EDIT-PAGE FORM
const MANAGED_PRODUCTS_ADDEDIT_SAVEBUTTON_KEY =
    'managed_products_addedit_appbar_save_button';

const K_MP_AD_ED_SAVE_BTN =
    MANAGED_PRODUCTS_ADDEDIT_SAVEBUTTON_KEY;

final MANAGED_PRODUCTS_ADDEDIT_FORM_GLOBALKEY = GlobalKey<FormState>();
final K_MP_FORM_GKEY = MANAGED_PRODUCTS_ADDEDIT_FORM_GLOBALKEY;

final MANAGED_PRODUCTS_PAGE_SCAFFOLD_GLOBALKEY = GlobalKey<ScaffoldState>();
final K_MP_SCFLD_GKEY  = MANAGED_PRODUCTS_PAGE_SCAFFOLD_GLOBALKEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE_KEY =
    'managed_products_addedit_field_title';
const K_MP_ADED_FLD_TIT = MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE_KEY =
    'managed_products_addedit_field_price';
const K_MP_ADED_FLD_PRICE = MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT_KEY =
    'managed_products_addedit_field_description';
const K_MP_ADED_FLD_DESC = MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_URL_KEY =
    'managed_products_addedit_field_url';
const K_MP_ADED_FLD_URL = MANAGED_PRODUCTS_ADDEDIT_FIELD_URL_KEY;
