import 'package:flutter/material.dart';

const MANAGED_PRODUCTS_ADDEDIT_APPBAR_ADDBUTTON_KEY = 'managed_products_addedit_appbar_add_button';
const K_MAN_PROD_ADDEDIT_ADD_BTN = MANAGED_PRODUCTS_ADDEDIT_APPBAR_ADDBUTTON_KEY;

const MANAGED_PRODUCTS_ADDEDIT_APPBAR_SAVEBUTTON_KEY =
    'managed_products_addedit_appbar_save_button';
const K_MAN_PROD_ADDEDIT_SAVE_BTN = MANAGED_PRODUCTS_ADDEDIT_APPBAR_SAVEBUTTON_KEY;

//MANAGED-PRODUCTS-ADD-EDIT-PAGE FORM
final MANAGED_PRODUCTS_ADDEDIT_FORM_GLOBAL_KEY = GlobalKey<FormState>();
final K_MAN_PROD_ADDEDIT_GLOBAL_KEY = MANAGED_PRODUCTS_ADDEDIT_FORM_GLOBAL_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE_KEY =
    'managed_products_addedit_field_title';
const K_MAN_PROD_ADDEDIT_FLD_TIT = MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE_KEY =
    'managed_products_addedit_field_price';
const K_MAN_PROD_ADDEDIT_FLD_PRICE = MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT_KEY =
    'managed_products_addedit_field_description';
const K_MAN_PROD_ADDEDIT_FLD_DESC = MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT_KEY;

const MANAGED_PRODUCTS_ADDEDIT_FIELD_URL_KEY =
    'managed_products_addedit_field_url';
const K_MAN_PROD_ADDEDIT_FLD_URL = MANAGED_PRODUCTS_ADDEDIT_FIELD_URL_KEY;
