//GENERAL PROPERTIES
const APP_TITLE = "My Shopp App";
const APP_DEBUG_CHECK = false;

//FLUSHBAR + GETX-SNACKBAR
const DURATION_SNACKBARS = 2000;

//DATE-FORMATS
//ORDERS-ITEM
const DATE_FORMAT = 'dd MMM yyyy - hh:mm';

const TIME_OUT = 5000;
