//GENERAL PROPERTIES
const APP_TITLE = "My Shopp App";
const APP_DEBUG_CHECK = false;

//FLUSHBAR + GETX-SNACKBAR
const DURATION = 1000;

//DATE-FORMATS
//ORDERS-ITEM
const DATE_FORMAT = 'dd MMM yyyy - hh:mm';

const TIME_OUT = 5000;

//DEFAULT-CIRCULAR-PROGRESS-INDICATOR-RADIUS
const CIRC_PROG_IND_RAD = 20.0;
