const OVERVIEW_GRID_ITEM_FAVORITE_BUTTON_KEY = 'ov01';
const OVERVIEW_GRID_ITEM_CART_BUTTON_KEY = 'ov02';
const OVERVIEW_GRID_PRODUCT_TITLE_KEY = 'ov03';
const OVERVIEW_BADGE_SHOP_CART_APPBAR_KEY = 'ov04';
const OVERVIEW_PAGE_TITLE_APPBAR_KEY = 'ov05';
const OVERVIEW_FILTER_FAVORITE_APPBAR_KEY = 'ov06';
const OVERVIEW_CUSTOM_FLUSH_NOTIFIER_UNDO_CART_ADD_KEY = 'ov07';
const FLUSH_NOTIFIER_SIMPLE_KEY = 'fb01';

const OV001 = OVERVIEW_GRID_ITEM_FAVORITE_BUTTON_KEY;
const OV002 = OVERVIEW_GRID_ITEM_CART_BUTTON_KEY;
const OV003 = OVERVIEW_GRID_PRODUCT_TITLE_KEY;
const OV004 = OVERVIEW_BADGE_SHOP_CART_APPBAR_KEY;
const OV005 = OVERVIEW_PAGE_TITLE_APPBAR_KEY;
const OV006 = OVERVIEW_FILTER_FAVORITE_APPBAR_KEY;
const OV007 = OVERVIEW_CUSTOM_FLUSH_NOTIFIER_UNDO_CART_ADD_KEY;

const FB001 = FLUSH_NOTIFIER_SIMPLE_KEY;



