const FIELD_TITLE_MIN_SIZE = 5;
const FIELD_TITLE_MAX_SIZE = 10;

const FIELD_DESC_MIN_SIZE = 10;
const FIELD_DESCRIPT_MAX_SIZE = 30;

const FIELD_BARCODE_SIZE = 30;

const FIELD_PRICE_MIN_SIZE = 0;
const FIELD_PRICE_MAX_SIZE = 10;

const FIELD_URL_MIN_SIZE = 10;
const FIELD_URL_MAX_SIZE = 135;

const FORMAT_DATE = r"[0-9]{2}(/)[0-9]{2}(/)[0-9]{4}";