

const AMOUNT = HINT_PRICE_FIELD;
const TITLE = HINT_TITLE_FIELD;
const DESCRIPT = HINT_DESCRIPTION_FIELD;
const URL = HINT_URL_FIELD;

const HINT_PRICE_FIELD = "00.00";
const HINT_TITLE_FIELD = "title";
const HINT_DESCRIPTION_FIELD = "Description";
const HINT_URL_FIELD = "Image Url";