const INVENTORY_ADDEDIT_TITLEPAGE_ADD = "Add Product";
const INVENTORY_ADDEDIT_TITLEPAGE_EDIT = "Edit Product";

const INVENTORY_ADDEDIT_FIELD_TITLE = "Title";
const INVENTORY_ADDEDIT_FIELD_PRICE = "Price";
const INVENTORY_ADDEDIT_FIELD_DESCRIPT = "Description";
const INVENTORY_ADDEDIT_IMAGE_TITLE = "Image";
const INVENTORY_ADDEDIT_FIELD_IMAGE_URL = "Image URL";

const INV_EDT_LBL_ADD_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_ADD;
const INV_EDT_LBL_EDIT_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_EDIT;

const INV_EDT_LBL_TITLE = INVENTORY_ADDEDIT_FIELD_TITLE;
const INV_EDT_LBL_PRICE = INVENTORY_ADDEDIT_FIELD_PRICE;
const INV_EDT_LBL_DESCR = INVENTORY_ADDEDIT_FIELD_DESCRIPT;
const INV_EDT_LBL_IMGURL = INVENTORY_ADDEDIT_FIELD_IMAGE_URL;
const INV_EDT_IMG_TIT = INVENTORY_ADDEDIT_IMAGE_TITLE;