import 'package:flutter/material.dart';

const INVENTORY_APPBAR_ADDPRODUCT_BUTTON_KEY = 'inventory_appbar_addbutton_key';
const K_INV_ADD_BTN = INVENTORY_APPBAR_ADDPRODUCT_BUTTON_KEY;

const INVENTORY_DELETEITEM_BUTTON_KEY = 'inventory_deleteitem_button_key';
const K_INV_DEL_BTN = INVENTORY_DELETEITEM_BUTTON_KEY;

const INVENTORY_UPDATEITEM_BUTTON_KEY = 'inventory_updateitem_button_key';
const K_INV_UPD_BTN = INVENTORY_UPDATEITEM_BUTTON_KEY;

const INVENTORY_ITEM_KEY = 'inventory_item_key';
const K_INV_ITEM_KEY = INVENTORY_ITEM_KEY;

//MANAGED-PRODUCTS-ADD-EDIT-PAGE FORM
const INVENTORY_ADDEDIT_VIEW_SAVEBUTTON_KEY = 'inventory_addedit_savebutton_key';
const K_INV_AD_ED_SAVE_BTN = INVENTORY_ADDEDIT_VIEW_SAVEBUTTON_KEY;

final INVENTORY_ADDEDIT_VIEW_FORM_GLOBALKEY = GlobalKey<FormState>();
final K_INV_FORM_GKEY = INVENTORY_ADDEDIT_VIEW_FORM_GLOBALKEY;

const INVENTORY_ADDEDIT_VIEW_FIELD_TITLE_KEY = 'inventory_addedit_field_title_key';
const K_INV_ADED_FLD_TIT = INVENTORY_ADDEDIT_VIEW_FIELD_TITLE_KEY;

const INVENTORY_ADDEDIT_VIEW_FIELD_PRICE_KEY = 'inventory_addedit_field_price_key';
const K_INV_ADED_FLD_PRICE = INVENTORY_ADDEDIT_VIEW_FIELD_PRICE_KEY;

const INVENTORY_ADDEDIT_VIEW_FIELD_DESCRIPT_KEY =
    'inventory_addedit_field_descript_key';
const K_INV_ADED_FLD_DESC = INVENTORY_ADDEDIT_VIEW_FIELD_DESCRIPT_KEY;

const INVENTORY_ADDEDIT_VIEW_FIELD_URL_KEY = 'inventory_addedit_field_url_key';
const K_INV_ADED_FLD_URL = INVENTORY_ADDEDIT_VIEW_FIELD_URL_KEY;
