const CART_TITLE_PAGE = "Your Cart";
const CART_LABEL_CARD = "Total";
const CART_LABEL_ORDER_NOW = "Order Now";
const CART_LABEL_KEEP_SHOP = "Keep Shopping";

const CART_TOOLTIP_CLEAR_ALL = "Clear All";

const CART_LABEL_ALERTDIALOG_DISMIS_CONFIRM = "Are you sure?";
const CART_MESSAGE_ALERTDIALOG_DISMISS_CONFIRM = "Do you really want remove: ";
const CART_MESSAGE_ALERTDIALOG_CLEAR_ALL = "Do you really want clear the cart?";
const CART_MESSAGE_ALERTDIALOG_ORDER_NOW = "Do you want Add your Order?";

const CRT_TIT_APPBAR = CART_TITLE_PAGE;
const CRT_LBL_CARD = CART_LABEL_CARD;
const CRT_LBL_ORD = CART_LABEL_ORDER_NOW;
const CRT_LBL_KEEP = CART_LABEL_KEEP_SHOP;

const CRT_CLEAR_TOOLT = CART_TOOLTIP_CLEAR_ALL;

const CRT_LBL_CONF_DISM = CART_LABEL_ALERTDIALOG_DISMIS_CONFIRM;
const CRT_MSG_CONF_DISM = CART_MESSAGE_ALERTDIALOG_DISMISS_CONFIRM;
const CRT_MSG_CONF_CLEAR_ALL = CART_MESSAGE_ALERTDIALOG_CLEAR_ALL;
const CRT_MSG_CONF_ORDER = CART_MESSAGE_ALERTDIALOG_ORDER_NOW;