const OVERVIEW_TITLE_PAGE_ALL = "Selling Items";
const OVERVIEW_TITLE_PAGE_FAVORITE = "Favorite Items";

const OVERVIEW_FAVORITES_FILTER_OPTION = 'Favorites';
const OVERVIEW_ALL_FILTER_OPTION = 'Show All';
const OVERVIEW_DETAIL_BUY_BUTTON = 'Add to Cart';

const OV_TIT_ALL_APPBAR = OVERVIEW_TITLE_PAGE_ALL;

const OV_TIT_FAV_APPBAR = OVERVIEW_TITLE_PAGE_FAVORITE;

const OV_TXT_POPUP_FAV = OVERVIEW_FAVORITES_FILTER_OPTION;
const OV_TXT_POPUP_ALL = OVERVIEW_ALL_FILTER_OPTION;
const OV_DET_BUY_BTN = OVERVIEW_DETAIL_BUY_BUTTON;