const DRAWER_COMPONENT_TITLE_APPBAR = "Hello Seller";

const DRAWER_COMPONENT_LABEL_PRODUCTS = "Products";

const DRAWER_COMPONENT_LABEL_CART = "Cart";
const DRAWER_COMPONENT_TEXT_CART_NO_PRODUCTS_YET = "No Products in the cart, "
    "Yet";

const DRAWER_COMPONENT_LABEL_ORDERS = "Orders";
const DRAWER_COMPONENT_TEXT_NO_ORDERS_YET = "No Orders were done, Yet";

const DRAWER_COMPONENT_LABEL_MANAGED_PRODUCTS = "Inventory";
const DRAWER_COMPONENT_TEXT_NO_MANAGED_PRODUCTS_YET = "No Managed Products, Yet";

const DRAWER_COMPONENT_LABEL_DARKTHEME = "Dark";

const DRW_TIT_APPBAR = DRAWER_COMPONENT_TITLE_APPBAR;

const DRW_LBL_PROD = DRAWER_COMPONENT_LABEL_PRODUCTS;

const DRW_LBL_CART = DRAWER_COMPONENT_LABEL_CART;
const DRW_TXT_CART = DRAWER_COMPONENT_TEXT_CART_NO_PRODUCTS_YET;

const DRW_LBL_ORD = DRAWER_COMPONENT_LABEL_ORDERS;
const DRW_TXT_ORD = DRAWER_COMPONENT_TEXT_NO_ORDERS_YET;

const DRW_LBL_MAN_PROD = DRAWER_COMPONENT_LABEL_MANAGED_PRODUCTS;
const DRW_TXT_NO_MAN_PROD_YET = DRAWER_COMPONENT_TEXT_NO_MANAGED_PRODUCTS_YET;

const DRW_LBL_DARKTHM = DRAWER_COMPONENT_LABEL_DARKTHEME;