


import '../../../core/texts_icons_provider/pages/overview.dart';

const OV_TIT_ALL_APPBAR = OVERVIEW_TITLE_ALL_APPBAR;
const OV_ICO_FAV = OVERVIEW_ICON_FAVORITES;

const OV_TIT_FAV_APPBAR = OVERVIEW_TITLE_FAVORITE_APPBAR;
const OV_ICO_NOFAV = OVERVIEW_ICON_NO_FAVORITES;

const OV_ICO_SHOP = OVERVIEW_ICON_SHOPPING_APPBAR;

const OV_ICO_POPUP = OVERVIEW_ICON_POPUP_APPBAR;
const OV_TXT_POPUP_FAV = OVERVIEW_TXT_POPUP_FAVORITES_APPBAR;
const OV_TXT_POPUP_ALL = OVERVIEW_TXT_POPUP_ALL_APPBAR;

const OV_ICO_NOTIF_FAV = OVERVIEW_ICON_NOTIFICATION_FAVORITES;
