
import '../../../pages_texts_icons/orders.dart';

const ORDERS_TIT_PAGE = ORDERS_TITLE_PAGE;
const ORDERS_LBL_CARD = ORDERS_LABEL_CARD;
const ORDERS_ICO_COLLAPSE = ORDERS_ICON_COLLAPSING;
const ORDERS_ICO_UNCOLLAPSE = ORDERS_ICON_UNCOLLAPSING;
