import '../../messages.dart';

const EMPTY_FIELD_INVALID_ERROR_MSG = EMPTY_FIELD_INVALIDATION_MESSAGE;

const FORMAT_NUMBER_INVALID_ERROR_MSG = FORMAT_NUMBER_INVALIDATION_MESSAGE;
const TEXT_NUMBER_INVALID_ERROR_MSG = ONLY_TEXTNUMBER_INVALIDATION_MESSAGE;
const PRICE_INVALID_ERROR_MSG = FORMAT_PRICE_INVALIDATION_MESSAGE;
const URL_INVALID_ERROR_MSG = FORMAT_URL_INVALIDATION_MESSAGE;

const SIZE_05_INVALID_ERROR_MSG = SIZE_05_INVALIDATION_MESSAGE;
const SIZE_10_INVALID_ERROR_MSG = SIZE_10_INVALIDATION_MESSAGE;
const SIZE_URL_INVALID_ERROR_MSG = SIZE_URL_INVALIDATION_MESSAGE;