import 'package:flutter/material.dart';

const INVENTORY_ADDEDIT_ICO_SAVE_APPBAR = Icon(Icons.save);

const INVENTORY_ADDEDIT_TITLEPAGE_ADD = "Add Product";
const INVENTORY_ADDEDIT_TITLEPAGE_EDIT = "Edit Product";

const INVENTORY_ADDEDIT_FIELD_TITLE = "Title";
const INVENTORY_ADDEDIT_FIELD_PRICE = "Price";
const INVENTORY_ADDEDIT_FIELD_DESCRIPT = "Description";
const INVENTORY_ADDEDIT_IMAGE_TITLE = "Image";
const INVENTORY_ADDEDIT_FIELD_IMAGE_URL = "Image URL";
