const MON_BUILD_ITEMSOVERVIEW_FAV = 'Built>=>  |>ITEMS_OVERVIEW_FAV_VIEW<|';
const MON_BUILD_ITEMSOVERVIEW_ALL = 'Built>=> |>ITEMS_OVERVIEW_ALL_VIEW<|';
const MON_BUILD_VIEW_CART = 'Built>=> |>CART_VIEW<|';
const MON_BUILD_VIEW_MANAGPRODUCTS = 'Built>=> |>MAN_PRODUCTS_VIEW<|';
const MON_BUILD_VIEW_ORDERS = 'Built>=> |>ORDERS_VIEW<|';
const MON_BUILD_VIEW_MANAGPRODSEDIT = 'Built>=> |>MAN_PRODUCTS_EDIT_VIEW<|';

const MON_BUILD_COMP_ITEMDETAIL = 'Built>=> |>|>ITEM_DETAIL_COMP|>';
const MON_BUILD_COMP_GRIDPRODITEM = 'Built>=> |>GRIDPRODUCTITEM_COMP<|';
const MON_BUILD_COMP_GRIDPRODUCTS = 'Built>=> |>GRIDPRODUCTS_COMP<|';
const MON_BUILD_COMP_ORDERCOLLAP_TILE = 'Built>=> |>ORDERCOLLAP_TILE_COMP<|';

const MON_BUILD_COMP_CARTVIEW_LISTVIEWBUILDER_CARTCARDITEM =
    'Built>=> |>LSTVIEWBUILD_CARTCARDITEM_COMP<|';
