import '../../../../texts_icons_provider/pages/managed_products/managed_product_edit.dart';

const MAN_PROD_EDIT_ICO_SAVE_APPBAR = MANAGED_PRODUCTS_EDIT_ICO_SAVE_APPBAR;
const MAN_PROD_EDIT_LBL_ADD_APPBAR = MANAGED_PRODUCTS_EDIT_LABEL_ADD_APPBAR;

const MAN_PROD_EDIT_LBL_EDIT = MANAGED_PRODUCTS_EDIT_LABEL_EDIT;
const MAN_PROD_EDIT_FLD_TITLE = MANAGED_PRODUCTS_EDIT_FIELD_TITLE;
const MAN_PROD_EDIT_FLD_PRICE = MANAGED_PRODUCTS_EDIT_FIELD_PRICE;
const MAN_PROD_EDIT_FLD_DESCR = MANAGED_PRODUCTS_EDIT_FIELD_DESCRIPT;
const MAN_PROD_EDIT_IMG_TIT = MANAGED_PRODUCTS_EDIT_IMAGE_TITLE;
const MAN_PROD_EDIT_FLD_IMG_URL = MANAGED_PRODUCTS_EDIT_FIELD_IMAGE_URL;
