
import '../../../../core/texts_icons_provider/pages/managed_products/managed_product_edit.dart';

const MAN_PROD_ADDEDIT_ICO_SAVE_APPBAR = MANAGED_PRODUCTS_ADDEDIT_ICO_SAVE_APPBAR;
const MAN_PROD_ADDEDIT_LBL_ADD_APPBAR = MANAGED_PRODUCTS_ADDEDIT_PAGE_ADD;
const MAN_PROD_ADDEDIT_LBL_EDT_APPBAR = MANAGED_PRODUCTS_ADDEDIT_PAGE_EDIT;

const MAN_PROD_ADDEDIT_FLD_TITLE = MANAGED_PRODUCTS_ADDEDIT_FIELD_TITLE;
const MAN_PROD_ADDEDIT_FLD_PRICE = MANAGED_PRODUCTS_ADDEDIT_FIELD_PRICE;
const MAN_PROD_ADDEDIT_FLD_DESCR = MANAGED_PRODUCTS_ADDEDIT_FIELD_DESCRIPT;
const MAN_PROD_ADDEDIT_FLD_IMG_URL = MANAGED_PRODUCTS_ADDEDIT_FIELD_IMAGE_URL;
const MAN_PROD_ADDEDIT_IMG_TIT = MANAGED_PRODUCTS_ADDEDIT_IMAGE_TITLE;
