import '../../texts_icons_provider/pages/components/drawwer.dart';

const DRW_TIT_APPBAR = DRAWER_COMPONENT_TITLE_APPBAR;

const DRW_LBL_PROD = DRAWER_COMPONENT_LABEL_PRODUCTS;
const DRW_ICO_PROD = DRAWER_COMPONENT_ICON_PRODUCTS;

const DRW_LBL_CART = DRAWER_COMPONENT_LABEL_CART;
const DRW_ICO_CART = DRAWER_COMPONENT_ICON_CART;
const DRW_TXT_CART = DRAWER_COMPONENT_TEXT_CART_NO_PRODUCTS_YET;

const DRW_LBL_ORD = DRAWER_COMPONENT_LABEL_ORDERS;
const DRW_ICO_ORD = DRAWER_COMPONENT_ICON_ORDERS;
const DRW_TXT_ORD = DRAWER_COMPONENT_TEXT_NO_ORDERS_YET;

const DRW_LBL_MAN_PROD = DRAWER_COMPONENT_LABEL_MANAGED_PRODUCTS;
const DRW_ICO_MAN_PROD = DRAWER_COMPONENT_ICON_MANAGED_PRODUCTS;
const DRW_TXT_NO_MAN_PROD_YET = DRAWER_COMPONENT_TEXT_NO_MANAGED_PRODUCTS_YET;

const DRW_LBL_DARKTHM = DRAWER_COMPONENT_LABEL_DARKTHEME;
const DRW_ICO_DARKTHM = DRAWER_COMPONENT_ICON_DARKTHEME;
