import '../../../../core/texts_icons_provider/pages/inventory/inventory_add_edit.dart';

const ICO_INV_EDT_SAVE_BTN_APPBAR = INVENTORY_ADDEDIT_ICO_SAVE_APPBAR;
const INV_EDT_LBL_ADD_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_ADD;
const INV_EDT_LBL_EDIT_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_EDIT;

const INV_EDT_LBL_TITLE = INVENTORY_ADDEDIT_FIELD_TITLE;
const INV_EDT_LBL_PRICE = INVENTORY_ADDEDIT_FIELD_PRICE;
const INV_EDT_LBL_DESCR = INVENTORY_ADDEDIT_FIELD_DESCRIPT;
const INV_EDT_LBL_IMGURL = INVENTORY_ADDEDIT_FIELD_IMAGE_URL;
const INV_EDT_IMG_TIT = INVENTORY_ADDEDIT_IMAGE_TITLE;

const INV_EDT_NO_IMG_TIT = INVENTORY_ADDEDIT_ICO_NOIMAGE_TITLE;
