import '../../../../core/texts_icons_provider/pages/inventory/inventory_add_edit.dart';

const INV_ADDEDIT_ICO_SAVE_APPBAR = INVENTORY_ADDEDIT_ICO_SAVE_APPBAR;
const INV_ADDEDIT_LBL_ADD_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_ADD;
const INV_ADDEDIT_LBL_EDT_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_EDIT;

const INV_ADDEDIT_FLD_TITLE = INVENTORY_ADDEDIT_FIELD_TITLE;
const INV_ADDEDIT_FLD_PRICE = INVENTORY_ADDEDIT_FIELD_PRICE;
const INV_ADDEDIT_FLD_DESCR = INVENTORY_ADDEDIT_FIELD_DESCRIPT;
const INV_ADDEDIT_FLD_IMG_URL = INVENTORY_ADDEDIT_FIELD_IMAGE_URL;
const INV_ADDEDIT_IMG_TIT = INVENTORY_ADDEDIT_IMAGE_TITLE;
