import '../../../../core/texts_icons_provider/pages/inventory/inventory_add_edit.dart';

const ICO_INV_ADEDT_SAVE_BTN_APPBAR = INVENTORY_ADDEDIT_ICO_SAVE_APPBAR;
const INV_ADEDT_LBL_ADD_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_ADD;
const INV_ADEDT_LBL_EDIT_APPBAR = INVENTORY_ADDEDIT_TITLEPAGE_EDIT;

const INV_ADEDT_FLD_TITLE = INVENTORY_ADDEDIT_FIELD_TITLE;
const INV_ADEDT_FLD_PRICE = INVENTORY_ADDEDIT_FIELD_PRICE;
const INV_ADEDT_FLD_DESCR = INVENTORY_ADDEDIT_FIELD_DESCRIPT;
const INV_ADEDT_FLD_IMGURL = INVENTORY_ADDEDIT_FIELD_IMAGE_URL;
const INV_ADEDT_IMG_TIT = INVENTORY_ADDEDIT_IMAGE_TITLE;

const INV_ADEDT_NO_IMG_TIT = INVENTORY_ADDEDIT_ICO_NOIMAGE_TITLE;
