const OVERVIEW_PAGE_SHOPCART_APPBAR_BUTTON_KEY = 'overview_page_shopcart_appbar_button_key';
const K_SHP_CART_APPBAR_BTN = OVERVIEW_PAGE_SHOPCART_APPBAR_BUTTON_KEY;

const CART_PAGE_ORDERSNOW_BUTTON_KEY = 'cart_page_ordersnow_button_key';
const K_CRT_ORD_NOW_BTN = CART_PAGE_ORDERSNOW_BUTTON_KEY;


