import '../../../texts_icons_provider/pages/cart.dart';

const CART_TIT_APPBAR = CART_TITLE_APPBAR;
const CART_LBL_CARD = CART_LABEL_CARD;
const CART_LBL_ORDER = CART_LABEL_ORDER;

const CART_ICO_CLEAR = CART_ICON_CLEAR_ALL;
const CART_ICO_CLEAR_TOOLTIP = CART_ICON_TOOLTIP_CLEAR_ALL;

const CART_ICO_DISMIS = CART_ICON_DISMISSING;
const CART_LBL_CONFIRM_DISMIS = CART_LABEL_DISMISSING_CONFIRMATION;
const CART_MSG_CONFIRM_DISMIS = CART_MESSAGE_DISMISSING_CONFIRMATION;
