import 'package:flutter/material.dart';

const DRAWER_COMPONENT_ICON_PRODUCTS = Icon(Icons.format_list_bulleted);

const DRAWER_COMPONENT_ICON_CART = Icon(Icons.shop);


const DRAWER_COMPONENT_ICON_ORDERS = Icon(Icons.payment);

const DRAWER_COMPONENT_ICON_MANAGED_PRODUCTS = Icon(Icons.edit);

const DRAWER_COMPONENT_ICON_DARKTHEME = Icon(Icons.lightbulb_outline);

const DRAWER_COMPONENT_ICON_NONE = Icon(Icons.hourglass_empty);

const DRW_ICO_CART = DRAWER_COMPONENT_ICON_CART;
const DRW_ICO_ORD = DRAWER_COMPONENT_ICON_ORDERS;
const DRW_ICO_MAN_PROD = DRAWER_COMPONENT_ICON_MANAGED_PRODUCTS;
const DRW_ICO_DARKTHM = DRAWER_COMPONENT_ICON_DARKTHEME;
const DRW_ICO_NONE = DRAWER_COMPONENT_ICON_NONE;
const DRW_ICO_PROD = DRAWER_COMPONENT_ICON_PRODUCTS;