import '../../../core/texts_icons_provider/pages/overview.dart';

const OV_TIT_ALL_APPBAR = OVERVIEW_TITLE_PAGE_ALL;
const OV_ICO_FAV = OVERVIEW_ICON_FAVORITES;

const OV_TIT_FAV_APPBAR = OVERVIEW_TITLE_PAGE_FAVORITE;
const OV_ICO_NOFAV = OVERVIEW_ICON_NO_FAVORITES;

const OV_ICO_SHOPCART = OVERVIEW_ICON_SHOPPING_APPBAR;

const OV_ICO_POPUP = OVERVIEW_ICON_POPUP_APPBAR;
const OV_TXT_POPUP_FAV = OVERVIEW_FAVORITES_FILTER_OPTION;
const OV_TXT_POPUP_ALL = OVERVIEW_ALL_FILTER_OPTION;

const OV_ICO_NOTIF_FAV = OVERVIEW_ICON_NOTIFICATION_FAVORITES;
